# 🟢 Apply this label to any change in the repo
unknown:
  - changed-files:
      - any-glob-to-any-file: '**'

# 📦 Go dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum

# 🧪 Go tests
tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_test.go'
          - "*test/**"
          - "*tests/**"
          - integration/**
  - title:
        - '^test(\(.+\))?:'
        - '^tests(\(.+\))?:'

# 📁 Command-line apps (Golang main packages)
CLI:
  - changed-files:
      - any-glob-to-any-file: cmd/**

# 📁 Internal packages (used only within this repo)
internal:
  - changed-files:
      - any-glob-to-any-file: internal/**

# 📁 Shared packages
packages:
  - changed-files:
      - any-glob-to-any-file: pkg/**

# 🧠 API or protobuf files
api:
  - changed-files:
      - any-glob-to-any-file:
          - api/**
          - proto/**

helm-chart:
  - changed-files:
      - any-glob-to-any-file:
          - charts/**
          - chart/**
          -
# 📚 Documentation and markdown
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - '**/*.md'
  - title:
        - '^docs(\(.+\))?:'
        - '^documentation(\(.+\))?:'
        - '^doc(\(.+\))?:'

# ⚙️ CI/CD workflows and GitHub Actions
ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
          - .github/actions/**
  - title:
        - '^ci(\(.+\))?:'
        - '^workflow(\(.+\))?:'

# 🛠️ DevOps, tools, and configuration
dev-ops:
  - changed-files:
      - any-glob-to-any-file:
          - Dockerfile
          - docker-compose.*
          - Makefile
          - .env*
          - scripts/**
          - config/**

# 🌱 Feature branches (e.g., feature/..., feat/...)
feature:
  - head-branch:
      - '^feature'
      - '^feat'
      - 'feature'
      - 'feat'
  - title: '^feat(\(.+\))?:'
  - title:
        - '^feat(\(.+\))?:'
        - '^feature(\(.+\))?:'
        - '^add(\(.+\))?:'

# 🐛 Bugfix branches (e.g., bugfix/..., fix/...)
bug:
  - title:
      - '^fix(\(.+\))?:'
      - '^bug(\(.+\))?:'
      - '^hotfix(\(.+\))?:'
  - head-branch:
      - '^bugfix'
      - '^fix'
      - 'bugfix'
      - 'fix'

# 🚀 Release PRs (e.g., feature/..., feat/...)
release:
  - head-branch:
      - '^release'
  - title:
        - '[Rr]elease'
        - '[Rr]elease[: ]'
        - 'pre[- ]?[Rr]elease'

# 🔁 Merge PRs to develop branch
develop:
  - base-branch: 'develop'

# ⚠️ Security-related changes
security:
  - changed-files:
      - any-glob-to-any-file:
          - SECURITY.md
          - '**/vuln*'
          - '**/cve*'

refactor:
  - title:
      - '^refactor(\(.+\))?:'
      - '^improve(\(.+\))?:'

chore:
  - title:
      - '^chore(\(.+\))?:'
      - '^meta(\(.+\))?:'


build:
  - title:
      - '^build(\(.+\))?:'
      - '^deps(\(.+\))?:'
      - '^dependency(\(.+\))?:'

