# 🟢 Apply this label to any change in the repo
AnyChange:
  - changed-files:
      - any-glob-to-any-file: '**'

# 🟦 Core Go files
Go:
  - changed-files:
      - any-glob-to-any-file: '**/*.go'

# 📦 Go dependencies
Dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum

# 🧪 Go tests
Tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_test.go'
          - test/**
          - tests/**

# 📁 Command-line apps (Golang main packages)
CLI:
  - changed-files:
      - any-glob-to-any-file: cmd/**

# 📁 Internal packages (used only within this repo)
Internal:
  - changed-files:
      - any-glob-to-any-file: internal/**

# 📁 Shared packages
Packages:
  - changed-files:
      - any-glob-to-any-file: pkg/**

# 🧠 API or protobuf files
API:
  - changed-files:
      - any-glob-to-any-file:
          - api/**
          - proto/**

# 📚 Documentation and markdown
Documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - '**/*.md'

# ⚙️ CI/CD workflows and GitHub Actions
CI:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
          - .github/actions/**

# 🛠️ DevOps, tools, and configuration
DevOps:
  - changed-files:
      - any-glob-to-any-file:
          - Dockerfile
          - docker-compose.*
          - Makefile
          - .env*
          - scripts/**
          - config/**

# 🌱 Feature branches (e.g., feature/..., feat/...)
feature:
  - head-branch:
      - '^feature'
      - '^feat'
      - 'feature'
      - 'feat'

# 🐛 Bugfix branches (e.g., bugfix/..., fix/...)
bugfix:
  - head-branch:
      - '^bugfix'
      - '^fix'
      - 'bugfix'
      - 'fix'

# 🚀 Release PRs targeting main
release:
  - base-branch: 'main'

# 🔁 Merge PRs to develop branch
develop:
  - base-branch: 'develop'

# ⚠️ Security-related changes
Security:
  - changed-files:
      - any-glob-to-any-file:
          - SECURITY.md
          - '**/vuln*'
          - '**/cve*'
