
# 📦 Go dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum

# 🧪 Go tests
tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_test.go'
          - "*test/**"
          - "*tests/**"
          - integration/**

# 🧠 API or protobuf files
api:
  - changed-files:
      - any-glob-to-any-file:
          - api/**
          - proto/**

helm-chart:
  - changed-files:
      - any-glob-to-any-file:
          - charts/**
          - chart/**

# 📚 Documentation and markdown
docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**

# ⚙️ CI/CD workflows and GitHub Actions
ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

# 🛠️ DevOps, tools, and configuration
dev-ops:
  - changed-files:
      - any-glob-to-any-file:
          - Dockerfile
          - docker-compose.*
          - Makefile
          - .env*
          - scripts/**
          - config/**

chore:
  - any:
      - 'scripts/**'
      - '.github/**'
      - 'Makefile'
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'


# 🌱 Feature branches (e.g., feature/..., feat/...)
feature:
  - head-branch:
      - '^feature'
      - '^feat'
      - 'feature'
      - 'feat'

# 🐛 Bugfix branches (e.g., bugfix/..., fix/...)
bug:
  - head-branch:
      - '^bugfix'
      - '^fix'
      - 'bugfix'
      - 'fix'

refactor:
  - head-branch:
      - '^refactor'
      - 'refactor'
      -
build:
  - head-branch:
      - '^build'
      - 'build'

perf:
  - head-branch:
      - '^perf'
      - 'perf'

release:
  - head-branch:
      - '^release'
      - 'release'
      - '^rel'
      - 'rel'

test:
  - head-branch:
      - '^test'
      - 'test'

# ⚠️ Security-related changes
security:
  - changed-files:
      - any-glob-to-any-file:
          - SECURITY.md
          - '**/vuln*'
          - '**/cve*'

