FROM alpine:3.22 AS tools_builder
RUN apk add --no-cache busybox && /bin/busybox --install -s /bin

FROM scratch

ARG TARGETOS
ARG TARGETARCH

WORKDIR /

COPY --from=tools_builder /bin/busybox /bin/busybox

RUN ["/bin/busybox", "--install", "-s", "/bin"]
RUN mkdir -p /binaries

COPY bin/*$TARGETOS-$TARGETARCH /binaries/

CMD ["/bin/ls", "-lrt", "/binaries/"]