FROM alpine AS tools_builder
RUN apk add --no-cache busybox && /bin/busybox --install -s /bin

FROM scratch

ARG TARGETOS
ARG TARGETARCH

WORKDIR /

COPY --from=tools_builder /bin/busybox /bin/busybox
RUN /bin/busybox --install -s /bin

RUN mkdir -p /binaries /bin

COPY bin/*$TARGETOS-$TARGETARCH /binaries/

CMD ["/bin/ls", "-lrt", "/binaries/"]