ARG DUMMY_SERVICE_IMAGE
ARG DUMMY_PLUGINS_IMAGE

FROM ghcr.io/openkcm/images/dummy-plugins:${DUMMY_PLUGINS_IMAGE} AS dummy-plugins

# --- Stage 2: main base image ---
FROM ghcr.io/openkcm/images/dummy-service:${DUMMY_SERVICE_IMAGE}

WORKDIR /

# Copy dependencies from other repos
COPY --from=dummy-plugins /binaries/dummy** /etc/plugins/dummy/

CMD ["./dummy-service"]