name: Release CMK

on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes
  workflow_call:
    secrets:
      OCM_PRIVATE_KEY:
        required: false
      COSIGN_PRIVATE_KEY:
        required: false
      COSIGN_PASSWORD:
        required: false
    inputs:
      image_signing_enabled:
        description: 'Enable image signing (true|false)'
        required: false
        default: false
        type: boolean # Use boolean type
      ocm_signing_enabled:
        description: 'Enable OCM signing (true|false)'
        required: false
        default: false
        type: boolean # Use boolean type

permissions:
  packages: write
  contents: write

jobs:
  push-composite:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for caching state
      packages: write
    steps:
      - name: Generate token from GitHub App
        id: generate-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42  # v2.1.4
        with:
          app-id: ${{ secrets.APP_PUSH_TAG_ID }}
          private-key: ${{ secrets.APP_PUSH_TAG_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-tags: true
          fetch-depth: 0
          submodules: recursive

      - name: Checkout build (taskfiles) repo
        run: |
          git clone --branch main --single-branch https://github.com/openkcm/build.git ./hack/common

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 #v2.0.0
        with:
          version: 3.x
          repo-token: ${{ steps.generate-token.outputs.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        timeout-minutes: 5
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          version: latest

      - name: Build & Push Image
        env:
          IMAGE_SIGNING_ENABLED: ${{ inputs.image_signing_enabled }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          OCM_SIGNING_ENABLED: ${{ inputs.ocm_signing_enabled }}
          OCM_PRIVATE_KEY: ${{ secrets.OCM_PRIVATE_KEY }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{  steps.generate-token.outputs.token }}
        run: |
          task build:apps[composite]:all --verbose
