name: ci
on:
  workflow_call:
    inputs:
      run_task_tests:
        description: "Run task tests"
        required: false
        type: boolean
        default: true
      run_makefile_tests:
        description: "Run makefile tests"
        required: false
        type: boolean
        default: false
      makefile_test_name:
        description: "Makefile task test name"
        required: false
        type: string
        default: "test"
      makefile_test_coverage_report_paths:
        description: "Coverage report paths (space-separated)"
        required: false
        type: string
        default: "cover.html cover.out"

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-and-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Init
        id: init
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "internal_pr=$([[ '${{ github.event.pull_request.head.repo.full_name }}' == '${{ github.repository }}' ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"
          else
            echo "internal_pr=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate token from GitHub App
        id: generate-token
        if: steps.init.outputs.internal_pr == 'true' && github.actor != 'dependabot[bot]'
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf  # v2.2.1
        with:
          app-id: ${{ secrets.APP_PUSH_TAG_ID }}
          private-key: ${{ secrets.APP_PUSH_TAG_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.generate-token.outputs.token || github.token }}
          fetch-tags: true
          fetch-depth: 0
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod

      - name: Checkout build (taskfiles) repo
        run: |
          git clone --branch main --single-branch https://github.com/openkcm/build.git ./hack/common

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 #v2.0.0
        with:
          version: 3.x
          repo-token: ${{ steps.generate-token.outputs.token || github.token }}

      - name: task validate
        run: task validate --verbose

      - name: task unit tests
        if: ${{ inputs.run_task_tests }}
        run: task test --verbose

      - name: makefile advanced tests
        if: ${{ inputs.run_makefile_tests }}
        run: |
          # Install bash if missing
          if ! command -v bash >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y bash
          fi
          
          # Run Makefile tests
          make "${{ inputs.makefile_test_name }}"

      - name: Save Metadata and Move Coverages
        if: always()
        run: |
          mkdir -p pr-metadata
          mkdir -p coverage
          
          # Only populate PR metadata if it is a Pull Request
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "${{ github.event.pull_request.number }}" > pr-metadata/pr_number
            echo "${{ github.event.pull_request.head.ref }}" > pr-metadata/pr_head_ref
            echo "${{ github.event.pull_request.base.ref }}" > pr-metadata/pr_base_ref
            echo "${{ github.event.pull_request.head.sha }}" > pr-metadata/pr_head_sha
          fi
          
          # Move coverage files and build a comma-separated list for Sonar
          SONAR_PATHS=""
          for file in ${{ inputs.makefile_test_coverage_report_paths }}; do
            if [ -f "$file" ]; then
              mv "$file" coverage/
              if [ -z "$SONAR_PATHS" ]; then
                SONAR_PATHS="coverage/$file"
              else
                SONAR_PATHS="$SONAR_PATHS,coverage/$file"
              fi
            fi
          done
          
          # Save the dynamic paths into the metadata folder
          echo "$SONAR_PATHS" > pr-metadata/coverage_paths

      - name: Debug Coverage Generation
        if: always()
        run: |
          echo "Looking for files defined in input: ${{ inputs.makefile_test_coverage_report_paths }}"
          echo "Current directory contents:"
          ls -la
          echo "Searching for any coverage files in all subdirectories:"
          find . -name "cover.out" -o -name "cover.html" -o -name "*.out"

      - name: Upload Coverages and PR Metadata
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: coverage-report
          path: |
            coverage/
            pr-metadata/
          if-no-files-found: warn
          retention-days: 1