name: REUSE Compliance Check

on: [push, pull_request, workflow_call]

permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5
